spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpabook
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hinbernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        # show_sql: true
    dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.SQL: debug